#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>

#define DIVIDE_13 1000000000000
#define DIVIDE_14 10000000000000
#define DIVIDE_15 100000000000000
#define DIVIDE_16 1000000000000000
#define EXIT_CARD_ERROR -1
#define PASS ;
#define START_AMEX 3
#define START_MASTER 5
#define START_VISA 4

/* PROTOTYPES */
int add_product_sums(int digit);
string check_number(long number, int num_digits);
int count_digits(long number);
bool lund_check(long number);

/* MAIN */
int main(void)
{
    string card_type = "INVALID";
    long number;
    int num_digits;

    number = get_long("Enter card number: ");
    printf("\n");

    /* get_long() returns strange error value */
    if (number == 9223372036854775807)
    {
        printf("%s\n", card_type);
        return EXIT_CARD_ERROR;
    }

    num_digits = count_digits(number);
    card_type = check_number(number, num_digits);

    printf("%s\n", card_type);

    return EXIT_SUCCESS;
}

/* HELPER FUNCTIONS */

/* Initial fetch of CC number */
long get_card_number(void)
{
    int card_number = -1;

    do
    {
        card_number = get_int("Enter the card number: ");
    }
    while (card_number < 0);
    printf("\n");

    return card_number;
}

/* Validate the number */
string check_number(long number, int num_digits)
{
    string card_type = "INVALID";
    int prefix;

    /* Check number of digits and first digit, verify if ok */
    if ((num_digits == 13) && (number / DIVIDE_13 == 4))
    /* Visa type 1: 13 digits, starts with 4 */
    {
        if (lund_check(number))
        {
            card_type = "VISA";
        }
    }
    else if ((num_digits == 16) && (number / DIVIDE_16 == 4))
    /* Visa type 2: 16 digits, starts with 4 */
    {
        if (lund_check(number))
        {
            card_type = "VISA";
        }
    }
    else if ((num_digits == 15) && (number / DIVIDE_15 == 3))
    /* Amex: 15 digits, starts with 3 */
    {
        /* Amex: only starts with 34 or 37 */
        prefix = number / DIVIDE_14;
        if ((prefix == 34) || (prefix == 37))
        {
            if (lund_check(number))
            {
                card_type = "AMEX";
            }
        }
    }
    else if ((num_digits == 16) && (number / DIVIDE_16 == 5))
    /* MasterCard: 16 digits, starts with 5 */
    {
        /* MC: only starts with 51, 52, 53, 54, or 55 */
        prefix = number / DIVIDE_15;
        if ((prefix == 51) ||
            (prefix == 52) ||
            (prefix == 53) ||
            (prefix == 54) ||
            (prefix == 55))
        {
            if (lund_check(number))
            {
                card_type = "MASTERCARD";
            }
        }
    }
    else
    {
        PASS;
    }

    return card_type;
}

/* Get the number of digits in the CC number */
int count_digits(long number)
{
    int num_digits = 0;
    long remainder = number;

    // Shift digits and count
    while (remainder > 10)
    {
        remainder /= 10;
        num_digits++;
    }

    // Check if not evenly divisible by 10
    if (remainder > 0)
    {
        num_digits++;
    }

    return num_digits;
}

bool lund_check(long number)
{
    int digit;
    bool is_valid;
    int product_sums = 0;
    long remainder = number;
    int sum = 0;
    int toggle = -1;

    // Shift digits and count
    while (remainder > 10)
    {
        digit = remainder % 10;
        remainder /= 10;

        if (toggle < 0) // First digit goes to sum
        {
            sum += digit;
        }
        else
        {
            product_sums += add_product_sums(digit);
        }
        toggle *= -1;
    }

    // Get the last digit
    if (remainder > 0)
    {
        if (toggle < 0) // Continue sequence
        {
            sum += remainder;
        }
        else
        {
            product_sums += add_product_sums(remainder);
        }
    }

    // Perform check. Valid if the last digit is 0
    is_valid = (sum + product_sums) % 10 == 0 ? true : false;
    return is_valid;
}

int add_product_sums(int digit)
{
    /* Multiply the digit by two, then sum the digits in the product */

    int product = digit * 2;
    int product_sum;

    if (product > 9)
    {
        product_sum = 1 + (product % 10);
    }
    else
    {
        product_sum = product;
    }

    return product_sum;
}

/*

BUILD AND TEST
make credit && for n in $(cat test_cards.txt) ; do echo $n | ./credit ; done

*/

/*

check50 cs50/problems/2025/x/credit
Results for cs50/problems/2025/x/credit generated by check50 v3.3.11
:) credit.c exists
:) credit.c compiles
:) identifies 378282246310005 as AMEX
:) identifies 371449635398431 as AMEX
:) identifies 5555555555554444 as MASTERCARD
:) identifies 5105105105105100 as MASTERCARD
:) identifies 4111111111111111 as VISA
:) identifies 4012888888881881 as VISA
:) identifies 4222222222222 as VISA
:) identifies 1234567890 as INVALID (invalid length, checksum, identifying digits)
:) identifies 369421438430814 as INVALID (invalid identifying digits)
:) identifies 4062901840 as INVALID (invalid length)
:) identifies 5673598276138003 as INVALID (invalid identifying digits)
:) identifies 4111111111111113 as INVALID (invalid checksum)
:) identifies 4222222222223 as INVALID (invalid checksum)
:) identifies 3400000000000620 as INVALID (AMEX identifying digits, VISA/Mastercard length)
:) identifies 430000000000000 as INVALID (VISA identifying digits, AMEX length)
To see more detailed results go to https://submit.cs50.io/check50/f51b470695812c540cb4eadf820d6e6d37cc8698

*/

