#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>

int main()
{
    string name;

    name = get_string("What's your name? ");

    printf("hello, %s\n", name);

    return EXIT_SUCCESS;
}

/*

check50 cs50/problems/2025/x/me
Results for cs50/problems/2025/x/me generated by check50 v3.3.11
:) hello.c exists
:) hello.c compiles
:) responds to name Mario
:) responds to name Peach
:) responds to name Bowser
To see more detailed results go to
https://submit.cs50.io/check50/cab50eb5a6ee48a71a46a17d8691046d1a1ee017

*/
