#include <stdio.h>

int main()
{

    printf("hello, world\n");

    return 0;
}

/*

world/ $ check50 cs50/problems/2025/x/world
Results for cs50/problems/2025/x/world generated by check50 v3.3.11
:) hello.c exists
:) hello.c compiles
:) hello.c prints "hello, world"
To see more detailed results go to
https://submit.cs50.io/check50/a519196aac30ec4bb5735458bc2a1362d44ce33b

*/
