#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>

#define QUARTER 25
#define DIME 10
#define NICKLE 5
#define PENNY 1

/* PROTOTYPES */
int get_target(void);
int count_coins(int target);

/* MAIN */
int main(void)
{
    int target = get_target();
    int num_coins = count_coins(target);

    printf("%d\n", num_coins);

    return EXIT_SUCCESS;
}

/* HELPERS */
int get_target(void)
{
    int target;

    printf("Enter change amount.\n");

    do
    {
        target = get_int("Enter an integer: ");
    }
    while (target < 0);
    printf("\n");

    return target;
}

int count_coins(int target)
{
    int current_target;
    int quarters = 0;
    int dimes = 0;
    int nickles = 0;
    int pennies = 0;
    int num_coins;

    current_target = target;

    while (current_target > 0)
    {
        if (current_target >= QUARTER)
        {
            quarters = current_target / QUARTER;
            current_target = current_target % QUARTER;
        }
        else if (current_target >= DIME)
        {
            dimes = current_target / DIME;
            current_target = current_target % DIME;
        }
        else if (current_target >= NICKLE)
        {
            nickles = current_target / NICKLE;
            current_target = current_target % NICKLE;
        }
        else
        {
            pennies = current_target;
            current_target = 0;
        }
    }

    num_coins = quarters + dimes + nickles + pennies;

    return num_coins;
}


/*

check50 cs50/problems/2025/x/cash
Results for cs50/problems/2025/x/cash generated by check50 v3.3.11
:) cash.c exists
:) cash.c compiles
:) input of 41 yields output of 4
:) input of 1 yields output of 1
:) input of 15 yields output of 2
:) input of 160 yields output of 7
:) input of 2300 yields output of 92
:) rejects a negative input like -1
:) rejects a non-numeric input of "foo"
:) rejects a non-numeric input of ""
To see more detailed results go to https://submit.cs50.io/check50/07b2056ce522c34a06a7fb35a3e077291ceca42c

*/
