#include <cs50.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define LETTER_COEFFICIENT 0.0588
#define SENTENCE_COEFFICIENT 0.296
#define OFFSET 15.8

int main(void)
{

    int spaces = 0;
    int sentences = 0;
    int letters = 0;
    int words = 0;
    int i = 0;
    float grade_level;
    float L;
    float S;
    string text;

    // Get the text
    text = get_string("Enter a text: ");

    // Count letters, spaces, sentences
    while (text[i] != '\0')
    {
        if (((text[i] >= 'A') && (text[i] <= 'Z')) || ((text[i] >= 'a') && (text[i] <= 'z')))
        {
            letters++;
        }
        else if (text[i] == ' ')
        {
            spaces++;
            words++;
        }
        else if ((text[i] == '.') || (text[i] == '!') || (text[i] == '?'))
        {
            sentences++;
        }

        i++;
    }

    // No final space, always at least one word
    words += 1;

    /*

    Calculate Coleman-Liau index

    CLI = (0.0588 * L) - (0.296 * S) - 15.8
    L = (letters / words) * 100
    S = (sentences / words) * 100

    */

    L = (letters / (float) words) * 100;
    S = (sentences / (float) words) * 100;
    grade_level = LETTER_COEFFICIENT * L - SENTENCE_COEFFICIENT * S - OFFSET;

    // Print out level
    if (grade_level < 1)
    {
        printf("Before Grade 1\n");
    }
    else if (grade_level < 16)
    {
        printf("Grade %d\n", (int) round(grade_level));
    }
    else
    {
        printf("Grade 16+\n");
    }

    return EXIT_SUCCESS;
}

/* TO TEST

while read -r line ; do echo $line | ./readability ; done < test.txt

*/

/* TEST OUTPUT

check50 cs50/problems/2025/x/readability
Results for cs50/problems/2025/x/readability generated by check50 v3.3.11
:) readability.c exists
:) readability.c compiles
:) handles single sentence with multiple words
:) handles punctuation within a single sentence
:) handles more complex single sentence
:) handles multiple sentences
:) handles multiple more complex sentences
:) handles longer passages
:) handles multiple sentences with different punctuation
:) handles questions in passage
:) handles reading level before Grade 1
:) handles reading level at Grade 16+
To see more detailed results go to https://submit.cs50.io/check50/c613d060d5b48f29d2681da2fd9ac88595d345a7

*/
