#include <cs50.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHAR_VALUE_OFFSET 97

// Scrable point values A-Z
const int points[] = {1, 3, 4, 2,  1, 4, 2, 4, 1, 8, 5, 1, 3,
                      1, 1, 3, 10, 1, 1, 1, 1, 4, 4, 8, 4, 10};

// FUNCTION PROTOTYPES
int get_points(string word);

// MAIN
int main(void)
{
    string player_one_word = get_string("Player 1: ");
    string player_two_word = get_string("Player 2: ");

    int player_one_points;
    int player_two_points;

    player_one_points = get_points(player_one_word);
    player_two_points = get_points(player_two_word);

    // Display results
    if (player_one_points > player_two_points)
    {

        printf("Player 1 wins!\n");
    }
    else if (player_one_points < player_two_points)
    {
        printf("Player 2 wins!\n");
    }
    else
    {
        printf("Tie!\n");
    }

    return EXIT_SUCCESS;
}

int get_points(string word)
{
    char current_char;
    int i;
    int points_total = 1;

    for (i = 0; i < strlen(word); i++)
    {
        current_char = word[i];
        current_char = tolower(current_char);

        if ((current_char >= 'a') && (current_char <= 'z'))
        {
            current_char -= CHAR_VALUE_OFFSET;
            points_total += points[(int) current_char];
        }
    }

    return points_total;
}


/*

check50 cs50/problems/2025/x/scrabble
Results for cs50/problems/2025/x/scrabble generated by check50 v3.3.11
:) scrabble.c exists
:) scrabble.c compiles
:) handles letter cases correctly
:) handles punctuation correctly
:) correctly identifies 'Question?' and 'Question!' as a tie
:) correctly identifies 'drawing' and 'illustration' as a tie
:) correctly identifies 'hai!' as winner over 'Oh,'
:) correctly identifies 'COMPUTER' as winner over 'science'
:) correctly identifies 'Scrabble' as winner over 'wiNNeR'
:) correctly identifies 'pig' as winner over 'dog'
:) correctly identifies 'Skating!' as winner over 'figure?'
To see more detailed results go to https://submit.cs50.io/check50/d46bde419cff17100c07085d4566f05a8b8ef5ff

*/
