#include <cs50.h>
#include <stdio.h>

#define SPACE ' '
#define BLOCK '#'

/* Prototypes */
int get_height(void);
void print_rows(int height);
void print_chars(char character, int num_chars);

/* Main */
int main(void)
{
    int height;

    height = get_height();
    print_rows(height);

    return 0;
}

void print_chars(char character, int num_chars)
{
    for (int i = 0; i < num_chars; i++)
    {
        printf("%c", character);
    }
}

void print_rows(int height)
{
    /* Print spaces followed by blocks to build pyramid

       sss#g#sss
       ss##g##ss
       s###g###s
       ####g####

    */

    int gap_size = 2;

    for (int h = 1; h <= height; h++)
    {
        /* Print leading spaces */
        print_chars(SPACE, height - h);

        /* Print blocks */
        print_chars(BLOCK, h);

        /* Print gap */
        print_chars(SPACE, gap_size);

        /* Print blocks */
        print_chars(BLOCK, h);

        printf("\n");
    }
}

int get_height(void)
{
    int height;

    printf("How high is the pyramid? \n");

    do
    {
        height = get_int("Enter a positive integer: ");
        printf("\n");
    }
    while (height < 1);

    return height;
}

/*

check50 cs50/problems/2025/x/mario/more
Results for cs50/problems/2025/x/mario/more generated by check50 v3.3.11
:) mario.c exists
:) mario.c compiles
:) rejects a height of -1
:) rejects a height of 0
:) handles a height of 1 correctly
:) handles a height of 2 correctly
:) handles a height of 8 correctly
:) rejects a height of -1, and then accepts a height of 2
:) rejects a non-numeric height of "foo"
:) rejects a non-numeric height of ""
To see more detailed results go to https://submit.cs50.io/check50/8c8577f6e08c098c5e88b86172e56cb2d0b2e481

*/
