#include <cs50.h>
#include <stdio.h>

/* Prototypes */
int get_height(void);
void print_rows(int height);


/* Main */
int main(void)
{
    int height;

    height = get_height();
    print_rows(height);

    return 0;
}

void print_rows(int height)
{
    /* Print spaces followed by blocks to build pyramid

       sss#
       ss##
       s###
       ####

    */

    int s;
    int i;

    for (int h = 1; h <= height; h++)
    {
        /* Print leading spaces */
        for (s = 0; s < height - h; s++)
        {
            printf(" ");
        }

        /* Print blocks */
        for (i = 0; i < h; i++)
        {
            printf("#");
        }

        printf("\n");
    }
}

int get_height(void)
{
    int height;

    printf("How high is the pyramid? \n");

    do
    {
         height = get_int("Enter a positive integer: ");
         printf("\n");
    }
    while (height < 1);

    return height;
}


/*

check50 cs50/problems/2025/x/mario/less
Results for cs50/problems/2025/x/mario/less generated by check50 v3.3.11
:) mario.c exists
:) mario.c compiles
:) rejects a height of -1
:) rejects a height of 0
:) handles a height of 1 correctly
:) handles a height of 2 correctly
:) handles a height of 8 correctly
:) rejects a height of -1, and then accepts a height of 2
:) rejects a non-numeric height of "foo"
:) rejects a non-numeric height of ""
To see more detailed results go to https://submit.cs50.io/check50/a0ce49a3f02a910ca84137e0e16402210b5333b1

*/
